steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sascha-playground-doit/content-moderation', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sascha-playground-doit/content-moderation']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'content-moderation', '--image', 'gcr.io/sascha-playground-doit/content-moderation', '--region', 'us-central1','--allow-unauthenticated', '--platform', 'managed', '--memory', '500Mi', '--max-instances', '5', '--update-env-vars', 'API=']
images:
- gcr.io/sascha-playground-doit/content-moderation